name: CovertVote Fabric Network
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: covertvotechannel
    contracts:
      - id: covertvote

organizations:
  - mspid: Org1MSP
    peers:
      - endpoint: localhost:7051
        tlsCACerts:
          path: '../network/crypto-config/peerOrganizations/org1.covertvote.com/peers/peer0.org1.covertvote.com/tls/ca.crt'
    identities:
      certificates:
        - name: 'User1'
          clientPrivateKey:
            path: '../network/crypto-config/peerOrganizations/org1.covertvote.com/users/User1@org1.covertvote.com/msp/keystore/priv_sk'
          clientSignedCert:
            path: '../network/crypto-config/peerOrganizations/org1.covertvote.com/users/User1@org1.covertvote.com/msp/signcerts/User1@org1.covertvote.com-cert.pem'
